---
apiVersion: v1
kind: Service
metadata:
  name: gt-api
spec:
  selector:
    app: gt-api
  ports:
    - port: 4000
      targetPort: 4000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gt-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gt-api
  template:
    metadata:
      labels:
        app: gt-api
    spec:
      volumes:
        - name: vault
          secret:
            secretName: app-secret
            items:
              - key: 'atlas.hcl'
                path: 'atlas.hcl'
      initContainers:
        - name: migrations-before-api-up
          image: gabtec/bluegreen-db:v2
          imagePullPolicy: Always
          volumeMounts:
            - name: vault
              mountPath: '/etc/vault'
          args:
            [
              'migrate',
              'apply',
              '-c',
              'file:///etc/vault/atlas.hcl',
              '--env',
              'k8s',
            ]
      containers:
        - name: gt-api
          image: gabtec/bluegreen-api:v1
          imagePullPolicy: Always
          env:
            - name: DB_USER
              value: admin
            - name: DB_PASSWORD
              # value: admin
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: DB_PASSWORD
            - name: DB_NAME
              value: deno_db
            - name: DB_HOST
              value: gt-db
            - name: DB_PORT
              value: '5432'
          ports:
            - containerPort: 4000
