apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ingress.yaml
  - green-app.yaml
  - blue-app.yaml

images:
  - name: gabtec/bluegreen
    newTag: b7cd31d211dab0a9c1ddd2f37c9cadbd6a5295c6
