name: build-deploy

on:
  push:
    branches: ['main']
    paths:
      - 'frontend/src/**'
    # paths-ignore:
    #   - '**.md'
    #   - 'k8s/**'
  # pull_request:
  #   branches: ['main']

jobs:
  # ------------------------------------------ j1
  build-and-publish: # TODO
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to the Registry
        uses: docker/login-action@v2 #v1
        with:
          username: ${{secrets.REG_USER}}
          password: ${{secrets.REG_PASSWD}}

      - name: Build and Push the Image
        uses: docker/build-push-action@v4 #v2
        with:
          context: ./frontend/
          push: true
          tags: gabtec/bluegreen:${{github.sha}}

      - name: Install Kustomize
        uses: imranismail/setup-kustomize@v2
      - name: Kustomize deployment image tag
        run: |
          cd k8s
          kustomize edit set image gabtec/bluegreen:${{ github.sha }}
          git config --local user.email "actions@github.com"
          git config --local user.name "CD Action"
          git add .
          git commit -m "ci: update `gabtec/bluegreen` image tag to `${{ github.sha }}`"
          git push
